;; load order is intentional
(setq-default debug-on-error t)
(require 'wpc-package)
(require 'wpc-misc)
(require 'ssh)
;; (require 'keyboard)
(require 'irc)
(require 'email)
(require 'keybindings)
(require 'window-manager)
(require 'wpc-ui)
(require 'wpc-dired)
(require 'wpc-org)
(require 'wpc-company)
(require 'wpc-shell)
(require 'wpc-language-support)
