[package]
name = "store-ref-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.0"
once_cell = "1.9.0"
proc_unroll = "0.1"

[dev-dependencies]

[dev-dependencies.proptest]
version = "1.0"
default-features = false
features = ["std"]
