[package]
name = "rlox"
version = "0.1.0"
authors = ["Vincent Ambo <mail@tazj.in>"]
edition = "2018"

[features]
# Enables debugging/disassembling in the bytecode interpreter. Off by
# default as it is quite spammy.
disassemble = []
