[package]
name = "weave"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["."]

# TODO(edef): cut down on required features, this is kind of a grab bag right now
[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
hashbrown = "0.14.3"
nix-compat = { version = "0.1.0", path = "../../../tvix/nix-compat" }
safer_owning_ref = "0.5.0"
rayon = "1.8.1"
rustc-hash = "2.0.0"
tvix-tracing = { version = "0.1.0", path = "../../../tvix/tracing" }
tracing = "0.1.40"
tracing-indicatif = "0.3.6"

[dependencies.polars]
version = "0.36.2"
features = ["parquet", "lazy", "streaming"]
