;; load order is intentional
(setq-default debug-on-error t)
(require 'wpc-package)
(require 'wpc-misc)
(require 'wpc-ssh)
(require 'wpc-keyboard)
(require 'wpc-irc)
(require 'wpc-email)
(require 'wpc-keybindings)
(require 'wpc-ui)
(require 'wpc-dired)
(require 'wpc-org)
(require 'wpc-company)
(require 'wpc-shell)
(require 'wpc-lisp)
(require 'wpc-haskell)
(require 'wpc-elixir)
(require 'wpc-nix)
(require 'wpc-rust)
(require 'wpc-clojure)
(require 'wpc-prolog)
