[package]
name = "tvix-store"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = { version = "1.3.1", features = ["rayon", "std"] }
itertools = "0.10.5"
maplit = "1.0.2"
prost = "0.11.2"
tonic = "0.8.2"

[build-dependencies]
prost-build = "0.11.2"
tonic-build = "0.8.2"
