[package]
name = "tvix-store-bin"
version = "0.1.0"
edition = "2021"

[lib]
name = "tvix_store"

[dependencies]
anyhow = "1.0.68"
blake3 = { version = "1.3.1", features = ["rayon", "std"] }
data-encoding = "2.3.3"
lazy_static = "1.4.0"
clap = { version = "4.0", features = ["derive", "env"] }
prost = "0.11.2"
sled = { version = "0.34.7", features = ["compression"] }
nix-compat = { path = "../nix-compat" }
thiserror = "1.0.38"
tokio-stream = "0.1.11"
tokio = { version = "1.23.0", features = ["rt-multi-thread"] }
tonic = "0.8.2"
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
fastcdc = "2.0.0"

[dependencies.tonic-reflection]
optional = true
version = "0.5.0"

[build-dependencies]
prost-build = "0.11.2"
tonic-build = "0.8.2"

[dev-dependencies]
test-case = "2.2.2"
tempfile = "3.3.0"
tonic-mock = { git = "https://github.com/brainrake/tonic-mock", branch = "bump-dependencies" }

[features]
default = ["reflection"]
reflection = ["tonic-reflection"]
