[package]
name = "tvix-store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
blake3 = { version = "1.3.1", features = ["rayon", "std"] }
data-encoding = "2.3.3"
lazy_static = "1.4.0"
clap = { version = "4.0", features = ["derive", "env"] }
prost = "0.11.2"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.11"
tonic = "0.8.2"

[dependencies.tonic-reflection]
optional = true
version = "0.5.0"

[build-dependencies]
prost-build = "0.11.2"
tonic-build = "0.8.2"

[dev-dependencies]
test-case = "2.2.2"

[features]
default = [
  "reflection"
]
reflection = [
  "tonic-reflection"
]
