[package]
name = "tvix-store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
async-stream = "0.3.5"
blake3 = { version = "1.3.1", features = ["rayon", "std"] }
bstr = "1.6.0"
bytes = "1.4.0"
clap = { version = "4.0", features = ["derive", "env"] }
count-write = "0.1.0"
data-encoding = "2.3.3"
futures = "0.3.30"
lazy_static = "1.4.0"
nix-compat = { path = "../nix-compat", features = ["async"] }
pin-project-lite = "0.2.13"
prost = "0.12.1"
opentelemetry = { version = "0.21.0", optional = true}
opentelemetry-otlp = { version = "0.14.0", optional = true }
opentelemetry_sdk = { version = "0.21.0", features = ["rt-tokio"], optional = true}
sha2 = "0.10.6"
sled = { version = "0.34.7" }
thiserror = "1.0.38"
tokio = { version = "1.32.0", features = ["fs", "macros", "net", "rt", "rt-multi-thread", "signal"] }
tokio-listener = { version = "0.3.2", features = [ "tonic011" ] }
tokio-stream = { version = "0.1.14", features = ["fs"] }
tokio-util = { version = "0.7.9", features = ["io", "io-util", "compat"] }
tonic = { version = "0.11.0", features = ["tls", "tls-roots"] }
tower = "0.4.13"
tracing = "0.1.37"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
tvix-castore = { path = "../castore" }
url = "2.4.0"
walkdir = "2.4.0"
async-recursion = "1.0.5"
reqwest = { version = "0.11.22", features = ["rustls-tls-native-roots", "stream"], default-features = false }
xz2 = "0.1.7"

[dependencies.tonic-reflection]
optional = true
version = "0.11.0"

[build-dependencies]
prost-build = "0.12.1"
tonic-build = "0.11.0"

[dev-dependencies]
test-case = "3.3.1"
tempfile = "3.3.0"
tokio-retry = "0.3.0"

[features]
default = ["fuse", "otlp", "tonic-reflection"]
fuse = ["tvix-castore/fuse"]
otlp = ["dep:opentelemetry", "dep:opentelemetry-otlp", "dep:opentelemetry_sdk"]
tonic-reflection = ["dep:tonic-reflection", "tvix-castore/tonic-reflection"]
virtiofs = ["tvix-castore/virtiofs"]
