;; entries :: '(entry ...)'
;; entry :: '(word translations note roots)
;; note :: (or nil string)
;; translations :: '(translation ...)
;; roots :: '(root ...)

'( ;; 1-50
  ("и" ("and" "though"))
  ("в" ("in" "at"))
  ("не" ("not"))
  ("он" ("he"))
  ("на" ("on" "it" "at" "to"))
  ("я" ("I"))
  ("что" ("what" "that" "why"))
  ("тот" ("that"))
  ("быть" ("to be"))
  ("с" ("with" "and" "from" "of"))
  ("а" ("while" "and" "but"))
  ("весь" ("all" "everything"))
  ("это" ("that" "this" "it"))
  ("как" ("how" "what" "as" "like"))
  ("она" ("she"))
  ("по" ("on" "along" "by"))
  ("но" ("but"))
  ("они" ("they"))
  ("к" ("to" "for" "by"))
  ("у" ("by" "with" "of"))
  ("ты" ("you"))
  ("из" ("from" "of" "in"))
  ("мы" ("we"))
  ("за" ("behind" "over" "at" "after"))
  ("вы" ("you"))
  ("так" ("so" "thus" "then"))
  ("же" ("and" "as for" "but" "same"))
  ("от" ("from" "of" "for"))
  ("сказать" ("to say" "to speak"))
  ("этот" ("this"))
  ("который" ("which" "who" "that"))
  ("мочь" ("be able" "can"))
  ("человек" ("man" "person"))
  ("о" ("of" "about" "against"))
  ("один" ("one" "some" "alone"))
  ("ещё" ("still" "yet"))
  ("бы" ("would"))
  ("такой" ("such" "so" "some"))
  ("только" ("only" "merely" "but"))
  ("себя" ("myself" "himself" "herself"))
  ("своё" ("one's own" "my" "our"))
  ("какой" ("what" "which" "how"))
  ("когда" ("when" "while" "as"))
  ("уже" ("already" "by now"))
  ("для" ("for" "to"))
  ("вот" ("here" "there" "this is" "that's")
   "calling attention to something")
  ("кто" ("who" "that" "some"))
  ("да" ("yes" "but") "affirmation (..., right?)")
  ("говорить" ("to say" "to tell" "to speak"))
  ("год" ("year"))

  ;; 51 - 100
  ("знать" ("to know" "be aware"))
  ("мой" ("my" "mine"))
  ("до" ("to" "up to" "about" "before"))
  ("или" ("or"))
  ("если" ("if"))
  ("время" ("time" "season"))
  ("рука" ("hand" "arm"))
  ("нет" ("no" "not" "but"))
  ("самый" ("most" "the very" "the same"))
  ("ни" ("not a" "not" "neither ... nor"))
  ("стать" ("to become" "begin" "come"))
  ("большой" ("big" "large" "important"))
  ("даже" ("even"))
  ("другой" ("other" "another" "different"))
  ("наш" ("our" "ours"))
  ("свой" ("one's own"))
  ("ну" ("now" "right" "well" "come on"))
  ("под" ("under" "for" "towards" "to"))
  ("где" ("where"))
  ("дело" ("business" "affair" "matter"))
  ("есть" ("to eat" "to be"))
  ("сам" ("oneself"))
  ("раз" ("time" "once" "since"))
  ("чтобы" ("that" "in order that"))
  ("два" ("two"))
  ("там" ("there" "then"))
  ("чем" ("than" "instead of")
   "чем ..., тем ...")
  ("глаз" ("eye" "sight"))
  ("жизнь" ("life"))
  ("первый" ("first" "front" "former"))
  ("день" ("day"))
  ("тут" ("here" "now" "then"))
  ("во" ("in" "at")
   "as particle also: wow, exactly, ...")
  ("ничто" ("nothing"))
  ("потом" ("afterwards" "then"))
  ("очень" ("very"))
  ("со" ("with"))
  ("хотеть" ("to want"))
  ("ли" ("whether" "if"))
  ("при" ("attached to" "in the presence of" "by" "about"))
  ("голова" ("head" "mind" "brains"))
  ("надо" ("over" "above" "ought to"))
  ("без" ("without"))
  ("видеть" ("to see"))
  ("идти" ("to go" "to come"))
  ("теперь" ("now" "nowadays"))
  ("тоже" ("also" "as well" "too"))
  ("стоять" ("to stand" "be" "stand up"))
  ("друг" ("friend"))
  ("дом" ("house" "home"))

  ;; 101-150
  ("сейчас" ("now" "presently" "soon"))
  ("можно" ("possible" "permitted"))
  ("после" ("after" "afterwards"))
  ("слово" ("word"))
  ("здесь" ("here"))
  ("думать" ("to think" "to believe"))
  ("место" ("place" "seat"))
  ("спросить" ("to ask"))
  ("через" ("through" "across"))
  ("лицо" ("face" "person"))
  ("что" ("what" "which" "that"))
  ("тогда" ("then"))
  ("хорошый" ("good" "nice"))
  ("каждый" ("every" "each"))
  ("новый" ("new" "modern"))
  ("жить" ("to live"))
  ("должный" ("due" "proper" "should"))
  ("смотреть" ("to look" "watch"))
  ("почему" ("why"))
  ("потому" ("that's why"))
  ("сторона" ("side" "party"))
  ("просто" ("simply"))
  ("нога" ("foot" "leg"))
  ("сидеть" ("to sit"))
  ("понять" ("to understand" "to realise"))
  ("иметь" ("to own" "to have"))
  ("конечный" ("final" "last"))
  ("делать" ("to do" "make"))
  ("вдруг" ("suddenly"))
  ("над" ("above" "over"))
  ("взять" ("to take"))
  ("никто" ("nobody"))
  ("понимать" ("to understand"))
  ("казаться" ("to seem" "to appear"))
  ("работа" ("work" "job"))
  ("три" ("three"))
  ("ваш" ("yours"))
  ("уж" ("really" "already"))
  ("земля" ("earth" "land" "soil"))
  ("конец" ("end" "distance"))
  ("несколько" ("several" "some"))
  ("час" ("hour" "time"))
  ("голос" ("voice"))
  ("город" ("town" "city"))
  ("последний" ("last" "the latest" "new"))

  ;; 151-200
  ("пока" ("for the present")) ;; TODO(tazjin): review
  ("хорошо" ("well"))
  ("давать" ("to give" "to grant"))
  ("вода" ("water"))
  ("более" ("more"))
  ("хотя" ("although"))
  ("всегда" ("always"))
  ("второй" ("second"))
  ("куда" ("where" "what for" "much"))
  ("пойти" ("to go"))
  ("стол" ("table" "desk" "board"))
  ("ребёнок" ("child" "kid" "infant"))
  ("увидеть" ("to see"))
  ("сила" ("strength" "force"))
  ("отец" ("father"))
  ("женщина" ("woman"))
  ("машина" ("car" "machine" "engine"))
  ("случай" ("case" "occasion" "incident"))
  ("ночь" ("night"))
  ("сразу" ("at once" "right away" "just"))
  ("мир" ("world" "peace"))
  ("совсем" ("quite" "entirely" "totally"))
  ("остаться" ("to remain" "to stay"))
  ("об" ("about" "of"))
  ("вид" ("appearance" "look" "view"))
  ("выйти" ("to go out" "to exit" "to come out" "to appear"))
  ("дать" ("to give"))
  ("работать" ("to work"))
  ("любить" ("to work"))
  ("старый" ("old"))
  ("почти" ("almost"))
  ("ряд" ("row" "line"))
  ("оказаться" ("find oneself" "turn out"))
  ("начало" ("beginning" "origin" "source"))
  ("твой" ("your" "yours"))
  ("вопрос" ("question" "matter" "problem"))
  ("много" ("many" "much"))
  ("война" ("war"))
  ("снова" ("again"))
  ("ответить" ("to answer" "to reply"))
  ("между" ("between" "among"))
  ("подумать" ("to think"))
  ("опять" ("again"))
  ("белый" ("white"))
  ("деньги" ("money"))
  ("значить" ("to mean" "to signify"))
  ("про" ("about" "for"))
  ("лишь" ("only" "as soon as"))
  ("минута" ("minute" "moment"))
  ("жена" ("wife"))
  )
