;; entries :: '(entry ...)'
;; entry :: '(word translations note roots)
;; note :: (or nil string)
;; translations :: '(translation ...)
;; roots :: '(root ...)

'( ;; 1-50
  ("и" ("and" "though"))
  ("в" ("in" "at"))
  ("не" ("not"))
  ("он" ("he"))
  ("на" ("on" "it" "at" "to"))
  ("я" ("I"))
  ("что" ("what" "that" "why"))
  ("тот" ("that"))
  ("быть" ("to be"))
  ("с" ("with" "and" "from" "of"))
  ("а" ("while" "and" "but"))
  ("весь" ("all" "everything") nil ("-весь-"))
  ("это" ("that" "this" "it"))
  ("как" ("how" "what" "as" "like"))
  ("она" ("she"))
  ("по" ("on" "along" "by"))
  ("но" ("but"))
  ("они" ("they"))
  ("к" ("to" "for" "by"))
  ("у" ("by" "with" "of"))
  ("ты" ("you"))
  ("из" ("from" "of" "in"))
  ("мы" ("we"))
  ("за" ("behind" "over" "at" "after"))
  ("вы" ("you"))
  ("так" ("so" "thus" "then"))
  ("же" ("and" "as for" "but" "same"))
  ("от" ("from" "of" "for"))
  ("сказать" ("to say" "to speak") nil ("-сказ-"))
  ("этот" ("this"))
  ("который" ("which" "who" "that"))
  ("мочь" ("be able" "can") nil ("-мочь-"))
  ("человек" ("man" "person"))
  ("о" ("of" "about" "against"))
  ("один" ("one" "some" "alone"))
  ("ещё" ("still" "yet"))
  ("бы" ("would"))
  ("такой" ("such" "so" "some"))
  ("только" ("only" "merely" "but"))
  ("себя" ("myself" "himself" "herself"))
  ("своё" ("one's own" "my" "our"))
  ("какой" ("what" "which" "how"))
  ("когда" ("when" "while" "as"))
  ("уже" ("already" "by now"))
  ("для" ("for" "to"))
  ("вот" ("here" "there" "this is" "that's")
   "calling attention to something")
  ("кто" ("who" "that" "some"))
  ("да" ("yes" "but") "affirmation (..., right?)")
  ("говорить" ("to say" "to tell" "to speak") nil ("-говор-"))
  ("год" ("year"))

  ;; 51 - 100
  ("знать" ("to know" "be aware") nil ("-зна-"))
  ("мой" ("my" "mine"))
  ("до" ("to" "up to" "about" "before"))
  ("или" ("or"))
  ("если" ("if"))
  ("время" ("time" "season") nil ("-врем-"))
  ("рука" ("hand" "arm"))
  ("нет" ("no" "not" "but"))
  ("самый" ("most" "the very" "the same"))
  ("ни" ("not a" "not" "neither ... nor"))
  ("стать" ("to become" "begin" "come"))
  ("большой" ("big" "large" "important"))
  ("даже" ("even"))
  ("другой" ("other" "another" "different") nil ("-друг-"))
  ("наш" ("our" "ours"))
  ("свой" ("one's own"))
  ("ну" ("now" "right" "well" "come on"))
  ("под" ("under" "for" "towards" "to"))
  ("где" ("where"))
  ("дело" ("business" "affair" "matter"))
  ("есть" ("to eat" "to be"))
  ("сам" ("oneself"))
  ("раз" ("time" "once" "since"))
  ("чтобы" ("that" "in order that"))
  ("два" ("two"))
  ("там" ("there" "then"))
  ("чем" ("than" "instead of")
   "чем ..., тем ...")
  ("глаз" ("eye" "sight"))
  ("жизнь" ("life") nil ("-жи-"))
  ("первый" ("first" "front" "former"))
  ("день" ("day"))
  ("тут" ("here" "now" "then"))
  ("во" ("in" "at")
   "as particle also: wow, exactly, ...")
  ("ничто" ("nothing"))
  ("потом" ("afterwards" "then"))
  ("очень" ("very"))
  ("со" ("with"))
  ("хотеть" ("to want"))
  ("ли" ("whether" "if"))
  ("при" ("attached to" "in the presence of" "by" "about"))
  ("голова" ("head" "mind" "brains") nil ("-голов-"))
  ("надо" ("over" "above" "ought to"))
  ("без" ("without"))
  ("видеть" ("to see") nil ("-вид-"))
  ("идти" ("to go" "to come"))
  ("теперь" ("now" "nowadays"))
  ("тоже" ("also" "as well" "too"))
  ("стоять" ("to stand" "be" "stand up"))
  ("друг" ("friend"))
  ("дом" ("house" "home"))

  ;; 101-150
  ("сейчас" ("now" "presently" "soon"))
  ("можно" ("possible" "permitted") nil ("-мочь-"))
  ("после" ("after" "afterwards"))
  ("слово" ("word"))
  ("здесь" ("here"))
  ("думать" ("to think" "to believe") nil ("-дум-"))
  ("место" ("place" "seat"))
  ("спросить" ("to ask") nil ("-прос-"))
  ("через" ("through" "across"))
  ("лицо" ("face" "person"))
  ("что" ("what" "which" "that"))
  ("тогда" ("then"))
  ("хороший" ("good" "nice") nil ("-хорош-"))
  ("каждый" ("every" "each"))
  ("новый" ("new" "modern") nil ("-нов-"))
  ("жить" ("to live") nil ("-жи-"))
  ("должный" ("due" "proper" "should"))
  ("смотреть" ("to look" "watch"))
  ("почему" ("why"))
  ("потому" ("that's why"))
  ("сторона" ("side" "party"))
  ("просто" ("simply"))
  ("нога" ("foot" "leg"))
  ("сидеть" ("to sit"))
  ("понять" ("to understand" "to realise"))
  ("иметь" ("to own" "to have"))
  ("конечный" ("final" "last"))
  ("делать" ("to do" "make"))
  ("вдруг" ("suddenly"))
  ("над" ("above" "over"))
  ("взять" ("to take"))
  ("никто" ("nobody"))
  ("понимать" ("to understand"))
  ("казаться" ("to seem" "to appear"))
  ("работа" ("work" "job"))
  ("три" ("three"))
  ("ваш" ("yours"))
  ("уж" ("really" "already"))
  ("земля" ("earth" "land" "soil"))
  ("конец" ("end" "distance"))
  ("несколько" ("several" "some"))
  ("час" ("hour" "time"))
  ("голос" ("voice"))
  ("город" ("town" "city"))
  ("последний" ("last" "the latest" "new"))

  ;; 151-200
  ("пока" ("for the present")) ;; TODO(tazjin): review
  ("хорошо" ("well") nil ("-хорош-"))
  ("давать" ("to give" "to grant"))
  ("вода" ("water"))
  ("более" ("more"))
  ("хотя" ("although"))
  ("всегда" ("always"))
  ("второй" ("second"))
  ("куда" ("where" "what for" "much"))
  ("пойти" ("to go") nil ("-й-"))
  ("стол" ("table" "desk" "board"))
  ("ребёнок" ("child" "kid" "infant"))
  ("увидеть" ("to see"))
  ("сила" ("strength" "force"))
  ("отец" ("father"))
  ("женщина" ("woman"))
  ("машина" ("car" "machine" "engine"))
  ("случай" ("case" "occasion" "incident"))
  ("ночь" ("night"))
  ("сразу" ("at once" "right away" "just"))
  ("мир" ("world" "peace"))
  ("совсем" ("quite" "entirely" "totally"))
  ("остаться" ("to remain" "to stay"))
  ("об" ("about" "of"))
  ("вид" ("appearance" "look" "view"))
  ("выйти" ("to go out" "to exit" "to come out" "to appear") nil ("-й-"))
  ("дать" ("to give"))
  ("работать" ("to work"))
  ("любить" ("to work"))
  ("старый" ("old"))
  ("почти" ("almost"))
  ("ряд" ("row" "line"))
  ("оказаться" ("find oneself" "turn out"))
  ("начало" ("beginning" "origin" "source"))
  ("твой" ("your" "yours"))
  ("вопрос" ("question" "matter" "problem") nil ("-прос-"))
  ("много" ("many" "much"))
  ("война" ("war"))
  ("снова" ("again"))
  ("ответить" ("to answer" "to reply"))
  ("между" ("between" "among"))
  ("подумать" ("to think"))
  ("опять" ("again"))
  ("белый" ("white"))
  ("деньги" ("money"))
  ("значить" ("to mean" "to signify") nil ("-зна-"))
  ("про" ("about" "for"))
  ("лишь" ("only" "as soon as"))
  ("минута" ("minute" "moment"))
  ("жена" ("wife"))

  ;; 201-300
  ("посмотреть" ("to watch" "to look" "to inspect") nil ("-смотр-"))
  ("правда" ("truth") nil ("-правд-"))
  ("главный" ("main" "chief") nil ("-голов-"))
  ("страна" ("country") nil ("-стран-"))
  ("свет" ("light" "world"))
  ("ждать" ("to wait"))
  ("мать" ("mother"))
  ("будто" ("as if" "as though"))
  ("никогда" ("never"))
  ("товариш" ("comrade" "friend"))
  ("дорога" ("road" "way" "journey"))
  ("однако" ("however" "although"))
  ("лежать" ("to lie" "to be situated"))
  ("именно" ("namely" "just" "exactly") nil ("-имя-"))
  ("окно" ("window"))
  ("никакой" ("no" "none"))
  ("найти" ("to find" "to discover") nil ("-й-"))
  ("писать" ("to write"))
  ("комната" ("room"))
  ("Москва" ("Moscow"))
  ("часть" ("part" "share" "department"))
  ("вообще" ("in general" "altogether" "on the whole") nil ("-общ-"))
  ("книга" ("book"))
  ("маленький" ("small" "little"))
  ("улица" ("street"))
  ("режить" ("to decide" "to solve"))
  ("далекий" ("distant" "remote"))
  ("душа" ("soul" "spirit"))
  ("чуть" ("hardly" "slightly"))
  ("вернуться" ("to return"))
  ("утро" ("morning"))
  ("некоторый" ("some"))
  ("считать" ("to count" "to consider"))
  ("сколько" ("how much" "how many"))
  ("помнить" ("to remember"))
  ("вечер" ("evening"))
  ("пол" ("floor" "gender"))
  ("таки" ("after all"))
  ("получить" ("to receive" "to get" "to obtain"))
  ("народ" ("people" "nation"))
  ("плечо" ("shoulder" "upper arm"))
  ("хоть" ("even" "if you want" "though"))
  ("сегодня" ("today"))
  ("бог" ("god"))
  ("вместе" ("together"))
  ("взгляд" ("look" "glance" "view"))
  ("ходить" ("to go" "to walk") nil ("-ход-"))
  ("зачем" ("what for" "why"))
  ("советский" ("Soviet"))
  ("русский" ("Russian"))
  ("бывать" ("to be" "to visit" "to happen"))
  ("полный" ("full" "complete" "whole"))
  ("прийти" ("to arrive" "to come") nil ("-й-"))
  ("палец" ("finger" "toe"))
  ("Россия" ("Russia"))
  ("любой" ("any" "every"))
  ("история" ("history" "story" "event"))
  ("наконец" ("finally" "at least"))
  ("мысль" ("thought" "idea"))
  ("узнать" ("to know" "to learn" "to recognise") nil ("-зна-"))
  ("назад" ("back" "backwards" "ago"))
  ("общий" ("general" "common") nil ("-общ-"))
  ("заметить" ("to notice" "to observe"))
  ("словно" ("as if" "like"))
  ("прошлый" ("past" "vergangen") nil ("-й-"))
  ("уйти" ("to leave" "to go away") nil ("-й-"))
  ("известный" ("well-known" "famous"))
  ("давно" ("long ago"))
  ("слышать" ("to hear"))
  ("слушать" ("to listen" "to hear"))
  ("бояться" ("to be afraid" "fear"))
  ("сын" ("son"))
  ("нельзя" ("it is impossible" "can't"))
  ("прямо" ("straight" "frankly"))
  ("долго" ("for a long time"))
  ("быстро" ("fast" "quickly"))
  ("лес" ("forest"))
  ("похожий" ("similar" "alike") nil ("-ход-"))
  ("пора" ("time" "pore"))
  ("пять" ("five"))
  ("глядеть" ("to look" "to gaze"))
  ("оно" ("it"))
  ("сесть" ("to sit"))
  ("имя" ("name") nil ("-имя-"))
  ("ж" ("and" "as for" "but"))
  ("разговор" ("conversation" "talk") nil ("-говор-"))
  ("тело" ("body"))
  ("молодой" ("young"))
  ("стена" ("wall"))
  ("красный" ("red"))
  ("читать" ("to read"))
  ("право" ("right"))
  ("старик" ("old man"))
  ("ранний" ("early"))
  ("хотеться" ("to want" "to like"))
  ("мама" ("mummy" "mum"))
  ("оставаться" ("to remain" "to stay"))
  ("высокий" ("tall" "high"))
  ("путь" ("way" "track" "path"))
  ("поэтому" ("therefore"))

  ;; 301-400
  ("совершенно" ("absolutely" "quite"))
  ("кроме" ("except" "besides"))
  ("тысяча" ("a thousand"))
  ("месяц" ("month"))
  ("брать" ("to take" "to hire"))
  ("написать" ("to write"))
  ("целый" ("intact" "whole" "entire"))
  ("огромный" ("huge" "enormous"))
  ("начинать" ("to begin"))
  ("спина" ("back"))
  ("настоящий" ("present" "real" "true"))
  ("пусть" ("let's" "though"))
  ("язык" ("tongue" "language"))
  ("точно" ("exactly"))
  ("среди" ("among"))
  ("чуствовать" ("to feel"))
  ("сердце" ("heart"))
  ("вести" ("to lead"))
  ("иногда" ("sometimes"))
  ("мальчик" ("boy"))
  ("успеть" ("to be in time" "to be successful"))
  ("небо" ("sky"))
  ("живой" ("living" "lively" "alive"))
  ("смерть" ("death"))
  ("продолжать" ("to continue"))
  ("девушка" ("girl"))
  ("образ" ("shape" "form" "image"))
  ("ко" ("to" "towards" "by"))
  ("забыть" ("to forget"))
  ("вокруг" ("around"))
  ("письмо" ("letter"))
  ("власть" ("power"))
  ("чёрный" ("black"))
  ("пройти" ("to pass" "go by" "be over") nil ("-й-"))
  ("появиться" ("to appear" "to show up"))
  ("воздух" ("air"))
  ("разный" ("different"))
  ("выходить" ("to go out" "to exit") "MR says 'to nurse'??" ("-ход-"))
  ("просить" ("to ask"))
  ("брат" ("brat"))
  ("собственный" ("one's own"))
  ("отношение" ("relationship" "attitude"))
  ("затем" ("then" "after that"))
  ("пытаться" ("to try"))
  ("показать" ("to show" "to display"))
  ("вспомнить" ("to remember" "to recall"))
  ("система" ("system"))
  ("четыре" ("four"))
  ("квартира" ("flat" "apartment"))
  ("держать" ("to hold" "to keep"))
  ("также" ("also" "as well" "too"))
  ("любовь" ("love"))
  ("солдат" ("soldier"))
  ("откуда" ("from where"))
  ("чтоб" ("that" "in order that"))
  ("называть" ("to call" "to name"))
  ("третий" ("third"))
  ("хозяин" ("master" "boss" "host"))
  ("вроде" ("like" "not unlike"))
  ("уходить" ("to leave" "to go away") nil ("-ход-"))
  ("подойти" ("to approach" "to come up") nil ("-й-"))
  ("поднять" ("to lift" "to raise"))
  ("спрашивать" ("to ask" "to inquire"))
  ("начальник" ("chief" "head" "superior"))
  ("оба" ("both"))
  ("бросить" ("to throw"))
  ("школа" ("school"))
  ("парень" ("boy" "fellow" "guy"))
  ("кровь" ("blood"))
  ("двадцать" ("twenty"))
  ("солнце" ("sun"))
  ("неделя" ("week"))
  ("послать" ("to send" "to dispatch"))
  ("находиться" ("to be found" "to turn up") nil ("-ход-"))
  ("ребята" ("guys" "children"))
  ("поставить" ("to put" "to place" "to set"))
  ("встать" ("to get up" "to rise" "to stand up"))
  ("например" ("for example" "for instance"))
  ("шаг" ("step"))
  ("мужчина" ("man" "male"))
  ("равно" ("alike" "in like manner"))
  ("нос" ("nose"))
  ("мало" ("little" "few"))
  ("внимание" ("attention"))
  ("капитан" ("captain" "master"))
  ("ухо" ("ear"))
  ("туда" ("to there"))
  ("сюда" ("to here"))
  ("играть" ("to play"))
  ("следовать" ("to follow" "to come next"))
  ("рассказать" ("to tell" "to narrate"))
  ("великий" ("great"))
  ("действительно" ("indeed" "really"))
  ("слишком" ("too much"))
  ("тяжёлый" ("heavy"))
  ("спать" ("to sleep"))
  ("оставить" ("to leave" "to abandon"))
  ("войти" ("to enter" "to come in") nil ("-й-"))
  ("длинный" ("long")))
