;; entries :: '(entry ...)'
;; entry :: '(word translations note roots)
;; note :: (or nil string)
;; translations :: '(translation ...)
;; roots :: '(root ...)

'( ;; 1-50
  ("и" ("and" "though"))
  ("в" ("in" "at"))
  ("не" ("not"))
  ("он" ("he"))
  ("на" ("on" "it" "at" "to"))
  ("я" ("I"))
  ("что" ("what" "that" "why"))
  ("тот" ("that"))
  ("быть" ("to be"))
  ("с" ("with" "and" "from" "of"))
  ("а" ("while" "and" "but"))
  ("весь" ("all" "everything"))
  ("это" ("that" "this" "it"))
  ("как" ("how" "what" "as" "like"))
  ("она" ("she"))
  ("по" ("on" "along" "by"))
  ("но" ("but"))
  ("они" ("they"))
  ("к" ("to" "for" "by"))
  ("у" ("by" "with" "of"))
  ("ты" ("you"))
  ("из" ("from" "of" "in"))
  ("мы" ("we"))
  ("за" ("behind" "over" "at" "after"))
  ("вы" ("you"))
  ("так" ("so" "thus" "then"))
  ("же" ("and" "as for" "but" "same"))
  ("от" ("from" "of" "for"))
  ("сказать" ("to say" "to speak"))
  ("этот" ("this"))
  ("который" ("which" "who" "that"))
  ("мочь" ("be able" "can"))
  ("человек" ("man" "person"))
  ("о" ("of" "about" "against"))
  ("один" ("one" "some" "alone"))
  ("ещё" ("still" "yet"))
  ("бы" ("would"))
  ("такой" ("such" "so" "some"))
  ("только" ("only" "merely" "but"))
  ("себя" ("myself" "himself" "herself"))
  ("своё" ("one's own" "my" "our"))
  ("какой" ("what" "which" "how"))
  ("когда" ("when" "while" "as"))
  ("уже" ("already" "by now"))
  ("для" ("for" "to"))
  ("вот" ("here" "there" "this is" "that's")
   "calling attention to something")
  ("кто" ("who" "that" "some"))
  ("да" ("yes" "but") "affirmation (..., right?)")
  ("говорить" ("to say" "to tell" "to speak"))
  ("год" ("year"))

  ;; 51 - 100
  ("знать" ("to know" "be aware"))
  ("мой" ("my" "mine"))
  ("до" ("to" "up to" "about" "before"))
  ("или" ("or"))
  ("если" ("if"))
  ("время" ("time" "season"))
  ("рука" ("hand" "arm"))
  ("нет" ("no" "not" "but"))
  ("самый" ("most" "the very" "the same"))
  ("ни" ("not a" "not" "neither ... nor"))
  ("стать" ("to become" "begin" "come"))
  ("большой" ("big" "large" "important"))
  ("даже" ("even"))
  ("другой" ("other" "another" "different"))
  ("наш" ("our" "ours"))
  ("свой" ("one's own"))
  ("ну" ("now" "right" "well" "come on"))
  ("под" ("under" "for" "towards" "to"))
  ("где" ("where"))
  ("дело" ("business" "affair" "matter"))
  ("есть" ("to eat" "to be"))
  ("сам" ("oneself"))
  ("раз" ("time" "once" "since"))
  ("чтобы" ("that" "in order that"))
  ("два" ("two"))
  ("там" ("there" "then"))
  ("чем" ("than" "instead of")
   "чем ..., тем ...")
  ("глаз" ("eye" "sight"))
  ("жизнь" ("life"))
  ("первый" ("first" "front" "former"))
  ("день" ("day"))
  ("тут" ("here" "now" "then"))
  ("во" ("in" "at")
   "as particle also: wow, exactly, ...")
  ("ничто" ("nothing"))
  ("потом" ("afterwards" "then"))
  ("очень" ("very"))
  ("со" ("with"))
  ("хотеть" ("to want"))
  ("ли" ("whether" "if"))
  ("при" ("attached to" "in the presence of" "by" "about"))
  ("голова" ("head" "mind" "brains"))
  ("надо" ("over" "above" "ought to"))
  ("без" ("without"))
  ("видеть" ("to see"))
  ("идти" ("to go" "to come"))
  ("теперь" ("now" "nowadays"))
  ("тоже" ("also" "as well" "too"))
  ("стоять" ("to stand" "be" "stand up"))
  ("друг" ("friend"))
  ("дом" ("house" "home"))
  )
