newline_style = "Unix"

# Default code with is 100 characters, comments should follow
# suit.
wrap_comments = true
comment_width = 100

# The default of this option creates hard-to-read nesting of
# conditionals, turn it off.
combine_control_expr = false

# Group imports by module, but no higher. This avoids hard-to-read
# nested use statements.
imports_granularity = "Module"

# Avoid vertical visual clutter by unnecessarily exploding
# block-like arguments.
overflow_delimited_expr = true

# Miscellaneous
format_code_in_doc_comments = true
normalize_comments = true
