[book]
authors = ["The Tvix Authors"]
language = "en"
multilingual = false
src = "src"
title = "Tvix Docs"

[preprocessor.plantuml]
# override the /usr/bin/plantuml default
plantuml-cmd = "plantuml"
use-data-uris = true
