[package]
name = "tvix-eval-jobs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["."]

[dependencies]
nix-compat = { path = "../../nix-compat" }
tvix-build = { path = "../../build" }
tvix-castore = { path = "../../castore" }
tvix-store = { path = "../../store", default-features = false, features = []}
tvix-eval = { path = "../../eval" }
tvix-glue = { path = "../../glue" }
tvix-tracing = { path = "../../tracing" }
clap = "4.5.20"
tracing = "0.1.40"
mimalloc = "0.1.43"
tokio = "1.40.0"
tracing-indicatif = "0.3.6"
serde_json = "1.0.128"
codemap = "0.1.3"
serde = "1.0.210"
thiserror = "1.0.64"
color-eyre = "0.6.3"
