[package]
name = "nix-compat-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.nix-compat]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "read"
path = "fuzz_targets/read.rs"
test = false
doc = false

[[bin]]
name = "copy"
path = "fuzz_targets/copy.rs"
test = false
doc = false
