[package]
name = "yddns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
crimp = "4087.0"
tokio = "*" # pulled in by yandex-cloud
yandex-cloud = "2023.6.13"
