[package]
name = "tvix-glue"
version = "0.1.0"
edition = "2021"

[dependencies]
data-encoding = "2.3.3"
nix-compat = { path = "../nix-compat" }
tvix-build = { path = "../build", default-features = false, features = []}
tvix-eval = { path = "../eval" }
tvix-castore = { path = "../castore" }
tvix-store = { path = "../store", default-features = false, features = []}
bytes = "1.4.0"
tracing = "0.1.37"
tokio = "1.28.0"
thiserror = "1.0.38"
sha2 = "0.10.8"

[dependencies.wu-manber]
git = "https://github.com/tvlfyi/wu-manber.git"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
lazy_static = "1.4.0"
tempfile = "3.8.1"
test-case = "2.2.2"

[[bench]]
name = "eval"
harness = false
