[package]
name = "tvix-glue"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.6.0"
bytes = "1.4.0"
data-encoding = "2.3.3"
nix-compat = { path = "../nix-compat" }
tvix-build = { path = "../build", default-features = false, features = []}
tvix-eval = { path = "../eval" }
tvix-castore = { path = "../castore" }
tvix-store = { path = "../store", default-features = false, features = []}
tracing = "0.1.37"
tokio = "1.28.0"
thiserror = "1.0.38"
serde = "1.0.195"
serde_json = "1.0"
sha2 = "0.10.8"

[dependencies.wu-manber]
git = "https://github.com/tvlfyi/wu-manber.git"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
lazy_static = "1.4.0"
pretty_assertions = "1.4.0"
rstest = "0.18.2"
tempfile = "3.8.1"
test-case = "3.3.1"

[features]
default = ["nix_tests"]
# Enables running the Nix language test suite from the original C++
# Nix implementation (at version 2.3) against Tvix.
nix_tests = []

[[bench]]
name = "eval"
harness = false
