install:
	source "${WPCARRO}/configs/install"

uninstall:
	source "${WPCARRO}/configs/uninstall"

list-broken-links:
	find "${HOME}" -maxdepth 1 -xtype l && \
	find "${HOME}/.config" -maxdepth 1 -xtype l
