[package]
name = "tgsa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
crimp = "4087.0"
rouille = { version = "3.5", default-features = false }
url = "2.3"
scraper = "0.13"
ego-tree = "0.6" # in tandem with 'scraper'
serde = "1.0"
serde_json = "1.0"
