[package]
name = "tvix-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.28.0"
tvix-eval = { path = "../eval" }
tvix-glue = { path = "../glue" }
tvix-store = { path = "../store", default-features = false, features = []}
serde = { version = "1.0", features = ["derive"] }
