[package]
name = "tvix-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
tvix-eval = { path = "../eval" }
serde = { version = "1.0", features = ["derive"] }
bstr = { version = "1.10.0", features = ["serde"] }
