[package]
name = "tvix-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
tvix-eval = { path = "../eval" }
serde = { workspace = true, features = ["derive"] }
bstr = { workspace = true, features = ["serde"] }
