[package]
name = "tvix-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
tvix-eval = { path = "../eval" }
<<<<<<< HEAD   (649ccd chore(clippy): fix clippy (lvl2: MachineApplicable, human-ai)
serde = { version = "1.0", features = ["derive"] }
bstr = { version = "1.8.0", features = ["serde"] }

[lints]
workspace = true
=======
serde = { workspace = true, features = ["derive"] }
bstr = { workspace = true, features = ["serde"] }
>>>>>>> BRANCH (e4378f feat(tvix/store): seekable nar renderer)
