[package]
name = "weave"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["."]

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
hashbrown = "0.14.3"
nix-compat = { version = "0.1.0", path = "../../nix-compat" }
rayon = "1.8.1"

[dependencies.polars]
version = "0.36.2"
features = ["ipc"]
