## Module generated by c2nim for nix_api_store.h

import ./nix_api_types

{.pragma: nix_api_store, header: "nix_api_store.h", importc: "nix_$1".}

proc libstore_init*(context: NixContext): nix_err {.nix_api_store.}

proc init_plugins*(context: NixContext): nix_err {.nix_api_store.}

proc store_open*(a1: NixContext; uri: cstring; params: ptr cstringArray): Store {.nix_api_store.}

proc store_free*(store: Store) {.nix_api_store.}

proc store_get_uri*(context: NixContext; store: Store; dest: cstring; n: cuint): nix_err {.nix_api_store.}

proc store_parse_path*(context: NixContext; store: Store; path: cstring): StorePath {.nix_api_store.}

proc store_path_free*(p: StorePath) {.nix_api_store.}

proc store_is_valid_path*(context: NixContext; store: Store; path: StorePath): bool {.nix_api_store.}

proc store_build*(context: NixContext; store: Store; path: StorePath; userdata: pointer; callback: proc (userdata: pointer; outname: cstring; `out`: cstring)): nix_err {.nix_api_store.}

proc store_get_version*(a1: NixContext; store: Store; dest: cstring; n: cuint): nix_err {.nix_api_store.}

