## Module generated by c2nim for nix_api_expr.h

import ./nix_api_types

{.pragma: nix_api_expr, header: "nix_api_expr.h", importc: "nix_$1".}

proc libexpr_init*(context: NixContext): nix_err {.nix_api_expr.}

proc expr_eval_from_string*(context: NixContext; state: State; expr: cstring; path: cstring; value: Value): nix_err {.nix_api_expr.}

proc value_call*(context: NixContext; state: State; fn: Value; arg: Value; value: Value): nix_err {.nix_api_expr.}

proc value_force*(context: NixContext; state: State; value: Value): nix_err {.nix_api_expr.}

proc value_force_deep*(context: NixContext; state: State; value: Value): nix_err {.nix_api_expr.}

proc state_create*(context: NixContext; searchPath: cstringArray; store: Store): State {.nix_api_expr.}

proc state_free*(state: State) {.nix_api_expr.}

proc gc_incref*(context: NixContext; `object`: pointer): nix_err {.nix_api_expr.}

proc gc_decref*(context: NixContext; `object`: pointer): nix_err {.nix_api_expr.}

proc gc_now*() {.nix_api_expr.}

proc gc_register_finalizer*(obj: pointer; cd: pointer; finalizer: proc (obj: pointer; cd: pointer)) {.nix_api_expr.}

