[package]
name = "tvix-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol_str = "0.1"
rustyline = "10.0.0"
dirs = "4.0.0"
path-clean = "0.1"
tabwriter = { version = "1.2", optional = true }
rowan = "*" # pinned by rnix

# rnix has not been released in a while (as of 2022-08-22), we will
# use it from git.
[dependencies.rnix]
git = "https://github.com/nix-community/rnix-parser.git"
rev = "614e7d4641e83ab7eb321d9ac5e3d12985f9f3ba"

[dev-dependencies]
criterion = "0.3.6"
test-generator = "0.3.0"
pretty_assertions = "1.2.1"
itertools = "0.10.3"

[features]
# Enables running the Nix language test suite from the original C++
# Nix implementation (at version 2.3) against Tvix.
nix_tests = []

# Enables printing compiled code and tracing the stack state at runtime.
disassembler = ["dep:tabwriter"]

[[bench]]
name = "eval"
harness = false

[profile.release-with-debug]
inherits = "release"
debug = true
