[package]
name = "tvix-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tvix_eval"

[[bin]]
name = "tvix-eval"
required-features = [ "repl" ]

[dependencies]
smol_str = "0.1"
rustyline = { version = "10.0.0", optional = true }
dirs = "4.0.0"
path-clean = "0.1"
tabwriter = "1.2"
rowan = "*" # pinned by rnix
codemap = "0.1.3"
codemap-diagnostic = "0.1.1"

# rnix has not been released in a while (as of 2022-09-01), we will
# use it from git.
[dependencies.rnix]
git = "https://github.com/nix-community/rnix-parser.git"
rev = "97b438e34be5211a4b48aeed9cc3ded489b4d6da"

[dev-dependencies]
criterion = "0.3.6"
test-generator = "0.3.0"
pretty_assertions = "1.2.1"
itertools = "0.10.3"
tempdir = "0.3.7"

[features]
default = [ "repl" ]

# Enables running the Nix language test suite from the original C++
# Nix implementation (at version 2.3) against Tvix.
nix_tests = []

# Enables building the binary (tvix-eval REPL)
repl = [ "dep:rustyline" ]

[[bench]]
name = "eval"
harness = false

[profile.release-with-debug]
inherits = "release"
debug = true
