[package]
name = "tvix-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnix = "0.10.2"
smol_str = "0.1"
rustyline = "10.0.0"
dirs = "4.0.0"
path-clean = "0.1"
tabwriter = { version = "1.2", optional = true }

[dev-dependencies]
criterion = "0.3.6"
test-generator = "0.3.0"

[features]
# Enables running the Nix language test suite from the original C++
# Nix implementation (at version 2.3) against Tvix.
nix_tests = []

# Enables printing compiled code and tracing the stack state at runtime.
disassembler = ["dep:tabwriter"]

[[bench]]
name = "eval"
harness = false
