# File: "Non-Sensitive Ads Review (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_Adsreview"
  max_wait_time_for_consult_secs: 43200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ad_review_request_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "ads_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^2941"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "unreviewed_ads_keywords_and_extensions"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "FEATURE"
    is_optional: false
    constant_value: "regular_review"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "BUSINESS_LANGUAGE"
    is_optional: false
    parent_frd_id: "^3906"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_Adsreview"
  max_wait_time_for_consult_secs: 43200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ad_review_request_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "ads_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^2941"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "unreviewed_ads_keywords_and_extensions"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "FEATURE"
    is_optional: false
    constant_value: "regular_review"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "BUSINESS_LANGUAGE"
    is_optional: false
    parent_frd_id: "^3906"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "Ads Review (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_Adsreview"
  max_wait_time_for_consult_secs: 43200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ad_review_request_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "ads_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "unreviewed_ads_keywords_and_extensions"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "FEATURE"
    is_optional: false
    constant_value: "regular_review"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "BUSINESS_LANGUAGE"
    is_optional: false
    parent_frd_id: "^3906"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_Adsreview"
  max_wait_time_for_consult_secs: 43200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ad_review_request_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "ads_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "unreviewed_ads_keywords_and_extensions"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "FEATURE"
    is_optional: false
    constant_value: "regular_review"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "BUSINESS_LANGUAGE"
    is_optional: false
    parent_frd_id: "^3906"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "Ad Review (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_Adsreview"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ad_review_request_autoconsult"
  }
  
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "ads_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "unreviewed_ads_keywords_and_extensions"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "FEATURE"
    is_optional: false
    constant_value: "regular_review"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "BUSINESS_LANGUAGE"
    is_optional: false
    parent_frd_id: "^3906"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "Review Account Under Review (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^2941"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "review_account_under_review"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "POLICY"
    is_optional: false
    signal_type: "^2356"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^2941"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "review_account_under_review"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "POLICY"
    is_optional: false
    signal_type: "^2356"
  }
}
# File: "Accounts Review Requests (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "ISSUE_DESCRIPTION"
    is_optional: false
    parent_frd_id: "^2941"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "POLICY"
    is_optional: false
    signal_type: "^2356"
  }
}
# File: "Review Suspended Account (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "rereview_suspended_account"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "POLICY"
    is_optional: false
    signal_type: "^2356"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "rereview_suspended_account"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "POLICY"
    is_optional: false
    signal_type: "^2356"
  }
}
# File: "Review Suspended Account (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "rereview_suspended_account"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "POLICY"
    is_optional: false
    signal_type: "^2356"
  }
}
# File: "Suspended Long Form (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.policy"
    is_optional: false
    signal_type: "^2356"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.website_req"
    is_optional: false
    parent_frd_id: "^1677"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.who_pays"
    is_optional: false
    parent_frd_id: "^14657"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.summary_of_issue"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.sample_keywords"
    is_optional: false
    parent_frd_id: "^1881"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_street"
    is_optional: false
    parent_frd_id: "^1880"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_town"
    is_optional: false
    parent_frd_id: "^1879"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_zip"
    is_optional: false
    parent_frd_id: "^1885"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_country_req"
    is_optional: false
    parent_frd_id: "^1886"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.business_desc"
    is_optional: false
    parent_frd_id: "^14660"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.countries_business_serve"
    is_optional: false
    parent_frd_id: "^14659"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.name"
    is_optional: false
    parent_frd_id: "^1665"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.owner_or_emp"
    is_optional: false
    parent_frd_id: "^14661"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.payment_option"
    is_optional: false
    parent_frd_id: "^1882"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.phone_number"
    is_optional: false
    parent_frd_id: "^30248"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.policy"
    is_optional: false
    signal_type: "^2356"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.website_req"
    is_optional: false
    parent_frd_id: "^1677"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.who_pays"
    is_optional: false
    parent_frd_id: "^14657"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.summary_of_issue"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.sample_keywords"
    is_optional: false
    parent_frd_id: "^1881"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_street"
    is_optional: false
    parent_frd_id: "^1880"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_town"
    is_optional: false
    parent_frd_id: "^1879"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_zip"
    is_optional: false
    parent_frd_id: "^1885"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_country_req"
    is_optional: false
    parent_frd_id: "^1886"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.business_desc"
    is_optional: false
    parent_frd_id: "^14660"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.countries_business_serve"
    is_optional: false
    parent_frd_id: "^14659"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.name"
    is_optional: false
    parent_frd_id: "^1665"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.owner_or_emp"
    is_optional: false
    parent_frd_id: "^14661"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.payment_option"
    is_optional: false
    parent_frd_id: "^1882"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.phone_number"
    is_optional: false
    parent_frd_id: "^30248"
  }
}
# File: "Suspended Long Form (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.policy"
    is_optional: false
    signal_type: "^2356"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.website_req"
    is_optional: false
    parent_frd_id: "^1677"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.who_pays"
    is_optional: false
    parent_frd_id: "^14657"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.summary_of_issue"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.sample_keywords"
    is_optional: false
    parent_frd_id: "^1881"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_street"
    is_optional: false
    parent_frd_id: "^1880"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_town"
    is_optional: false
    parent_frd_id: "^1879"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_zip"
    is_optional: false
    parent_frd_id: "^1885"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_country_req"
    is_optional: false
    parent_frd_id: "^1886"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.business_desc"
    is_optional: false
    parent_frd_id: "^14660"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.countries_business_serve"
    is_optional: false
    parent_frd_id: "^14659"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.name"
    is_optional: false
    parent_frd_id: "^1665"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.owner_or_emp"
    is_optional: false
    parent_frd_id: "^14661"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.payment_option"
    is_optional: false
    parent_frd_id: "^1882"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.phone_number"
    is_optional: false
    parent_frd_id: "^30248"
  }
}
# File: "Copyright (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "POLICY"
    is_optional: false
    constant_value: "copyrights"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "POLICY"
    is_optional: false
    constant_value: "copyrights"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "Copyright (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "REQUEST"
    is_optional: false
    constant_value: "certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "POLICY"
    is_optional: false
    constant_value: "copyrights"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "INDENTIFIER_COMPLEXITY"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "EU Election Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Germany"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Netherlands"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Spain"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Check Republic"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "United Kingdom"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Germany"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Netherlands"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Spain"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Check Republic"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "United Kingdom"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
# File: "EU Election Certification #2 (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "hard"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "hard"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
# File: "EU Election Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: ""Germany" or "Netherlands" or "Spain" or "Check Republic" or "United Kingdom" # TODO(wpcarro): scrape.attribute_id_for could not find the ID."
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
# File: "EU Election Certification #2 (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
# File: "US Election Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.country"
    is_optional: false
    constant_value: "united_states_of_america"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.country"
    is_optional: false
    constant_value: "united_states_of_america"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
# File: "US Election Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.country"
    is_optional: false
    constant_value: "united_states_of_america"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
# File: "IN Election Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "Neo.country"
    is_optional: false
    constant_value: "india"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "Neo.country"
    is_optional: false
    constant_value: "india"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "IN Election Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "Neo.country"
    is_optional: false
    constant_value: "india"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "NY Election Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "us_election_ads_new_york_only"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.country"
    is_optional: false
    constant_value: "united_states_of_america"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.product"
    is_optional: false
    constant_value: "google_ads"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "us_election_ads_new_york_only"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.country"
    is_optional: false
    constant_value: "united_states_of_america"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.product"
    is_optional: false
    constant_value: "google_ads"
  }
}
# File: "NY Election Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "us_election_ads_new_york_only"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.country"
    is_optional: false
    constant_value: "united_states_of_america"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "Ticket Seller Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "event_ticket_reseller"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "event_ticket_reseller"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Ticket Seller Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "event_ticket_reseller"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Pharma Certification EMEA (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "online_pharmacy_certification_required"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "online_pharmacy_certification_required"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "Pharma Certification EMEA (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "online_pharmacy_certification_required"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
}
# File: "CSFP Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "complex_speculative_financial_policy"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "complex_speculative_financial_policy"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "CSFP Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "complex_speculative_financial_policy"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Social Casino Games Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "social_casino_games"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "social_casino_games"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Social Casino Games Certification (NonOlympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "social_casino_games"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Gambling Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "online_gambling"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "online_gambling"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Gambling Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "online_gambling"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Addiction Services Certification (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "addiction_services"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "addiction_services"
  }
}
# File: "Addiction Services Certification (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "addiction_services"
  }
}
# File: "HTML5 Application (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_HTML5_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.request"
    is_optional: false
    constant_value: "whitelisting"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.component"
    is_optional: false
    constant_value: "html5_ads"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_HTML5_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.request"
    is_optional: false
    constant_value: "whitelisting"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.component"
    is_optional: false
    constant_value: "html5_ads"
  }
}
# File: "HTML5 Application (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_HTML5_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.request"
    is_optional: false
    constant_value: "whitelisting"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.component"
    is_optional: false
    constant_value: "html5_ads"
  }
}
# File: "Free Desktop Software Policy (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "unwanted_software"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "unwanted_software"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Free Desktop Software Policy (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 259200
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "unwanted_software"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
}
# File: "Untrustworthy Promotions (Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.policy"
    is_optional: false
    signal_type: "^2356"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.website_req"
    is_optional: false
    parent_frd_id: "^1677"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.who_pays"
    is_optional: false
    parent_frd_id: "^14657"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.summary_of_issue"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.sample_keywords"
    is_optional: false
    parent_frd_id: "^1881"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_street"
    is_optional: false
    parent_frd_id: "^1880"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_town"
    is_optional: false
    parent_frd_id: "^1879"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_zip"
    is_optional: false
    parent_frd_id: "^1885"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_country_req"
    is_optional: false
    parent_frd_id: "^1886"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.business_desc"
    is_optional: false
    parent_frd_id: "^14660"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.countries_business_serve"
    is_optional: false
    parent_frd_id: "^14659"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.name"
    is_optional: false
    parent_frd_id: "^1665"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.owner_or_emp"
    is_optional: false
    parent_frd_id: "^14661"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.payment_option"
    is_optional: false
    parent_frd_id: "^1882"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.phone_number"
    is_optional: false
    parent_frd_id: "^30248"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "GOOGLE_ADS_INTERNAL_CUSTOMER_ID"
    is_optional: false
    signal_type: "^1421"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.policy"
    is_optional: false
    signal_type: "^2356"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.website_req"
    is_optional: false
    parent_frd_id: "^1677"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.who_pays"
    is_optional: false
    parent_frd_id: "^14657"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.summary_of_issue"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.sample_keywords"
    is_optional: false
    parent_frd_id: "^1881"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_street"
    is_optional: false
    parent_frd_id: "^1880"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_town"
    is_optional: false
    parent_frd_id: "^1879"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_zip"
    is_optional: false
    parent_frd_id: "^1885"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_country_req"
    is_optional: false
    parent_frd_id: "^1886"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.business_desc"
    is_optional: false
    parent_frd_id: "^14660"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.countries_business_serve"
    is_optional: false
    parent_frd_id: "^14659"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.name"
    is_optional: false
    parent_frd_id: "^1665"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.owner_or_emp"
    is_optional: false
    parent_frd_id: "^14661"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.payment_option"
    is_optional: false
    parent_frd_id: "^1882"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.phone_number"
    is_optional: false
    parent_frd_id: "^30248"
  }
}
# File: "Untrustworthy Promotions (Non-Olympus)"
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_accountappeals"
  max_wait_time_for_consult_secs: 172800
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_accountappeals_autoconsult"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "accounts_review"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.policy"
    is_optional: false
    signal_type: "^2356"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.website_req"
    is_optional: false
    parent_frd_id: "^1677"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.who_pays"
    is_optional: false
    parent_frd_id: "^14657"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.summary_of_issue"
    is_optional: false
    parent_frd_id: "^5305"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.sample_keywords"
    is_optional: false
    parent_frd_id: "^1881"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_street"
    is_optional: false
    parent_frd_id: "^1880"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_town"
    is_optional: false
    parent_frd_id: "^1879"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_address_zip"
    is_optional: false
    parent_frd_id: "^1885"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.billing_country_req"
    is_optional: false
    parent_frd_id: "^1886"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.business_desc"
    is_optional: false
    parent_frd_id: "^14660"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.countries_business_serve"
    is_optional: false
    parent_frd_id: "^14659"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.name"
    is_optional: false
    parent_frd_id: "^1665"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.owner_or_emp"
    is_optional: false
    parent_frd_id: "^14661"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.payment_option"
    is_optional: false
    parent_frd_id: "^1882"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "Form.phone_number"
    is_optional: false
    parent_frd_id: "^30248"
  }
}
#################################################################
# csv_to_proto: Test failure.
#################################################################
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Germany"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Netherlands"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Spain"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Check Republic"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "United Kingdom"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Germany"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Netherlands"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Spain"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "Check Republic"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
consult_settings {
  taxonomy_id: 9249441
  view_id: "Routing - Ads_certs"
  max_wait_time_for_consult_secs: 86400
  reroute_on_customer_interaction: true
  parent_lookup_frds {
    id: "^88149"
    value: "ads_certs_autoconsult"
  }
  parent_lookup_frds {
    id: "^87379"
    value: "olympus_plus"
  }
  parent_lookup_frds {
    id: "^16296"
    value: "United Kingdom"
  }
  parent_return_routing_frds {
    id: "ROBOT_WORKFLOW_STATE"
    value: "automation_escalate"
  }
  consult_routing_frds {
    id: "ORGANIZATION"
    value: "trust_safety"
  }
  consult_routing_frds {
    id: "VERTICAL"
    value: "ads"
  }
  consult_routing_frds {
    id: "REQUEST_TYPE"
    value: "Certifications"
  }
  inputs {
    type: PARENT_FRD
    consult_frd_id: "neo.country"
    is_optional: false
    parent_frd_id: "^16296"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.policy"
    is_optional: false
    constant_value: "elections"
  }
  inputs {
    type: CONSTANT
    consult_frd_id: "neo.complexity"
    is_optional: false
    constant_value: "easy"
  }
  inputs {
    type: SIGNAL
    consult_frd_id: "neo.product"
    is_optional: false
    signal_type: "^68613"
  }
}
