CREATE TABLE IF NOT EXISTS Movies (
  title TEXT NOT NULL,
  year INTEGER,
  PRIMARY KEY (title)
);

INSERT INTO Movies (title, year) VALUES ('Spirited Away', 2001);
INSERT INTO Movies (title, year) VALUES ('Andhadhun', 2018);
INSERT INTO Movies (title, year) VALUES ('Dangal', 2016);
INSERT INTO Movies (title, year) VALUES ('Avengers: Infinity War', 2019);
INSERT INTO Movies (title, year) VALUES ('Alien', 1979);
INSERT INTO Movies (title, year) VALUES ('The Great Dictator', 1940);
INSERT INTO Movies (title, year) VALUES ('City Lights', 1931);
INSERT INTO Movies (title, year) VALUES ('Kimi no na wa.', NULL);
INSERT INTO Movies (title, year) VALUES ('Taare Zameen Par', 2007);
INSERT INTO Movies (title, year) VALUES ('Babam ve Oglum', 2005);
INSERT INTO Movies (title, year) VALUES ('Aliens', 1986);
INSERT INTO Movies (title, year) VALUES ('Das Boot', 1981);
INSERT INTO Movies (title, year) VALUES ('Witness for the Prosecution', 1957);
INSERT INTO Movies (title, year) VALUES ('Sunset Blvd.', 1950);
INSERT INTO Movies (title, year) VALUES ('Neon Genesis Evangelion: The End of Evangelion', 2005);
INSERT INTO Movies (title, year) VALUES ('Children of Heaven', 1999);
INSERT INTO Movies (title, year) VALUES ('The Bandit', 1996);
INSERT INTO Movies (title, year) VALUES ('To Kill a Mockingbird', 1962);
INSERT INTO Movies (title, year) VALUES ('Lawrence of Arabia', 1962);
INSERT INTO Movies (title, year) VALUES ('Yojimbo', 1961);
INSERT INTO Movies (title, year) VALUES ('North by Northwest', 1959);
INSERT INTO Movies (title, year) VALUES ('Vertigo', 1958);
INSERT INTO Movies (title, year) VALUES ('Singing in the Rain', 1952);
INSERT INTO Movies (title, year) VALUES ('Ikiru', 1952);
INSERT INTO Movies (title, year) VALUES ('Rashomon', 1950);
INSERT INTO Movies (title, year) VALUES ('All About Eve', 1950);
INSERT INTO Movies (title, year) VALUES ('Double Indemnity', 1944);
INSERT INTO Movies (title, year) VALUES ('Citizen Kane', 1941);
INSERT INTO Movies (title, year) VALUES ('M', NULL);
INSERT INTO Movies (title, year) VALUES ('Metropolis', 1927);
INSERT INTO Movies (title, year) VALUES ('The Kid', 1921);
INSERT INTO Movies (title, year) VALUES ('PK', 2014);
INSERT INTO Movies (title, year) VALUES ('Rang De Basanti', 2006);
INSERT INTO Movies (title, year) VALUES ('Howls Moving Castle', 2004);
INSERT INTO Movies (title, year) VALUES ('Come and See', 1985);
INSERT INTO Movies (title, year) VALUES ('Ran', NULL);
INSERT INTO Movies (title, year) VALUES ('Andrei Rublev', 1966);
INSERT INTO Movies (title, year) VALUES ('Judgment at Nuremberg', 1961);
INSERT INTO Movies (title, year) VALUES ('Some Like It Hot', 1959);
INSERT INTO Movies (title, year) VALUES ('Wild Strawberries', 1957);
INSERT INTO Movies (title, year) VALUES ('The Seventh Seal', 1957);
INSERT INTO Movies (title, year) VALUES ('The Bridge on the River Kwai', 1957);
INSERT INTO Movies (title, year) VALUES ('On the Waterfront', 1954);
INSERT INTO Movies (title, year) VALUES ('Dial M for Murder', 1954);
INSERT INTO Movies (title, year) VALUES ('Tokyo Story', 1953);
INSERT INTO Movies (title, year) VALUES ('The Third Man', 1949);
INSERT INTO Movies (title, year) VALUES ('The Treasure of the Sierra Madre', 1948);
INSERT INTO Movies (title, year) VALUES ('Mr. Smith Goes to Washington', 1939);
INSERT INTO Movies (title, year) VALUES ('Sunrise: A Song of Two Humans', 1927);
INSERT INTO Movies (title, year) VALUES ('The General', 1926);
INSERT INTO Movies (title, year) VALUES ('The Gold Rush', 1925);
INSERT INTO Movies (title, year) VALUES ('Sherlock Jr.', 1924);
INSERT INTO Movies (title, year) VALUES ('Wild Tales', 2014);
INSERT INTO Movies (title, year) VALUES ('Hacksaw Ridge', 2016);
INSERT INTO Movies (title, year) VALUES ('Song of the Sea', 2014);
INSERT INTO Movies (title, year) VALUES ('The Help', 2011);
INSERT INTO Movies (title, year) VALUES ('Before Sunset', 2004);
INSERT INTO Movies (title, year) VALUES ('Memories of Murder', 2003);
INSERT INTO Movies (title, year) VALUES ('In the Mood for Love', 2000);
INSERT INTO Movies (title, year) VALUES ('La Haine', 1995);
INSERT INTO Movies (title, year) VALUES ('Before Sunrise', 1995);
INSERT INTO Movies (title, year) VALUES ('Three Colours: Red', 1994);
INSERT INTO Movies (title, year) VALUES ('Akira', 1988);
INSERT INTO Movies (title, year) VALUES ('Laputa: Castle in the Sky', 1986);
INSERT INTO Movies (title, year) VALUES ('Paris, Texas', 1984);
INSERT INTO Movies (title, year) VALUES ('Nausicaa of the Valley of the Wind', 1984);
INSERT INTO Movies (title, year) VALUES ('Gandhi', 1982);
INSERT INTO Movies (title, year) VALUES ('Fanny and Alexander', 1982);
INSERT INTO Movies (title, year) VALUES ('Stalker', 1979);
INSERT INTO Movies (title, year) VALUES ('Rocky', 1976);
INSERT INTO Movies (title, year) VALUES ('Network', 1976);
INSERT INTO Movies (title, year) VALUES ('Butch Cassidy and the Sundance Kid', 1969);
INSERT INTO Movies (title, year) VALUES ('Persona', 1966);
INSERT INTO Movies (title, year) VALUES ('The 400 Blows', 1959);
INSERT INTO Movies (title, year) VALUES ('Ben-Hur', 1959);
INSERT INTO Movies (title, year) VALUES ('The Nights of Cabiria', 1957);
INSERT INTO Movies (title, year) VALUES ('Les Diaboliques', 1955);
INSERT INTO Movies (title, year) VALUES ('The Wages of Fear', 1953);
INSERT INTO Movies (title, year) VALUES ('The Best Years of Our Lives', 1946);
INSERT INTO Movies (title, year) VALUES ('The Maltese Falcon', 1941);
INSERT INTO Movies (title, year) VALUES ('Rebecca', NULL);
INSERT INTO Movies (title, year) VALUES ('The Grapes of Wrath', 1940);
INSERT INTO Movies (title, year) VALUES ('It Happened One Night', 1934);
INSERT INTO Movies (title, year) VALUES ('La passion de Jeanne dArc', 1928);
