#!/usr/bin/env bash

configs="$DOTFILES/configs"

case $(hostname) in
  # desktop
  wpcarro.lon.corp.google.com)
    (cd "$configs/desktop" && stow --target="$HOME" *);;
  # laptop
  wpcarro.roam.googlers.com)
    (cd "$configs/laptop" && stow --target="$HOME" *);;
  # cloudtop
  wpcarro.c.googlers.com)
    (cd "$configs/cloudtop" && stow --target="$HOME" *);;
esac

(cd "$configs/shared" && stow --target="$HOME" *)
