#!/usr/bin/env bash

configs="$HOME/dotfiles/configs"

if [[  $(uname) == 'Darwin' ]]; then
  (cd "$configs/os_x" && stow --target="$HOME" *)
elif [[ $(uname) == 'Linux' ]]; then
  (cd "$configs/linux" && stow --target="$HOME" *)
fi

(cd "$configs/shared" && stow --target="$HOME" *)
