[package]
name = "achilles"
version = "0.1.0"
authors = ["Griffin Smith <root@gws.fyi>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bimap = "0.6.0"
clap = { version = "3", features = ["derive"] }
derive_more = "0.99.11"
inkwell = { git = "https://github.com/TheDan64/inkwell", features = ["llvm14-0"], rev = "6ab2b19e1b90be55fa4f9f056f29bd1ed557b990" }
itertools = "0.10.0"
lazy_static = "1.4.0"
llvm-sys = "140.0"
nom = "6.1.2"
nom-trace = { git = "https://github.com/glittershark/nom-trace", branch = "nom-6" }
pratt = "0.3.0"
proptest = "1.0.0"
test-strategy = "0.1.1"
thiserror = "1.0.24"
void = "1.0.2"

[dev-dependencies]
crate-root = "0.1.3"
pretty_assertions = "0.7.1"
