site_name: Volga Sprint
site_description: 'A week of Nix hacking near the Volga'
site_url: 'https://volgasprint.org'
repo_name: '//web/volgasprint'
repo_url: 'https://code.tvl.fyi/tree/web/volgasprint'
theme:
  name: material
  logo: assets/logos/volgasprint_nix.svg
  favicon: assets/logos/volgasprint_nix.svg
  palette:
    primary: black
    accent: '#FBFBFB'
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips
    - toc.integrate
nav:
  - Home: index.md
copyright: Copyright &copy; 2024 <a href="https://tvl.fyi">The TVL Community</a>
markdown_extensions:
  - tables
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
