[package]
name = "nix-compat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = ["futures-util"]

[dependencies]
bstr = { version = "1.6.0", features = ["alloc", "unicode", "serde"] }
data-encoding = "2.3.3"
futures-util = { version = "0.3.28", features = ["io"], optional = true }
glob = "0.3.0"
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.6"
thiserror = "1.0.38"

[dev-dependencies]
futures = { version = "0.3.28", default-features = false, features = ["executor"] }
lazy_static = "1.4.0"
serde_json = "1.0"
test-case = "2.2.2"
criterion = { version = "0.4", features = ["html_reports"] }
hex-literal = "0.4.1"
pretty_assertions = "1.4.0"
zstd = "^0.9.0"

[dev-dependencies.test-generator]
# This fork of test-generator adds support for cargo workspaces, see
# also https://github.com/frehberg/test-generator/pull/14
git = "https://github.com/JamesGuthrie/test-generator.git"
rev = "82e799979980962aec1aa324ec6e0e4cad781f41"

[[bench]]
name = "derivation_parse_aterm"
harness = false

[[bench]]
name = "narinfo_parse"
harness = false
