[package]
name = "nix-compat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
data-encoding = "2.3.3"
glob = "0.3.0"
sha2 = "0.10.6"
thiserror = "1.0.38"

[dev-dependencies]
test-case = "2.2.2"
