## Module generated by c2nim for nix_api_util.h

import ./nix_api_types

{.pragma: nix_api_util, header: "nix_api_util.h", importc: "nix_$1".}
{.pragma: importUtil, header: "nix_api_util.h", importc.}

var
  NIX_OK* {.importUtil.}: cint
  NIX_ERR_UNKNOWN* {.importUtil.}: cint
  NIX_ERR_OVERFLOW* {.importUtil.}: cint
  NIX_ERR_KEY* {.importUtil.}: cint
  NIX_ERR_NIX_ERROR* {.importUtil.}: cint

proc c_context_create*(): NixContext {.nix_api_util.}

proc c_context_free*(context: NixContext) {.nix_api_util.}

proc libutil_init*(context: NixContext): nix_err {.nix_api_util.}

proc setting_get*(context: NixContext; key: cstring; value: cstring; n: cint): nix_err {.nix_api_util.}

proc setting_set*(context: NixContext; key: cstring; value: cstring): nix_err {.nix_api_util.}

proc version_get*(): cstring {.nix_api_util.}

proc err_msg*(context: NixContext; ctx: NixContext; n: ptr cuint): cstring {.nix_api_util.}

proc err_info_msg*(context: NixContext; read_context: NixContext; value: cstring; n: cint): nix_err {.nix_api_util.}

proc err_name*(context: NixContext; read_context: NixContext; value: cstring; n: cint): nix_err {.nix_api_util.}

proc err_code*(read_context: NixContext): nix_err {.nix_api_util.}

proc set_err_msg*(context: NixContext; err: nix_err; msg: cstring): nix_err {.nix_api_util.}
