# prevents a false-positive lint on our types containing bytes::Bytes
# https://rust-lang.github.io/rust-clippy/master/index.html#/mutable_key_type
ignore-interior-mutability = [
  "bytes::Bytes",
  "tvix_castore::digests::B3Digest"
]
