[package]
name = "tvix-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tvix"
path = "src/main.rs"

[dependencies]
tvix-eval = { path = "../eval" }
tvix-derivation = { path = "../derivation" }
rustyline = "10.0.0"
clap = { version = "4.0", features = ["derive", "env"] }
tvix-store-bin = { path = "../store" }
dirs = "4.0.0"
smol_str = "0.1"
aho-corasick = "0.7"
ssri = "7.0.0"
data-encoding = "2.3.3"
thiserror = "1.0.38"
