[package]
name = "tvix-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tvix"
path = "src/main.rs"

[dependencies]
tvix-eval = { path = "../eval" }
rustyline = "10.0.0"
clap = { version = "4.0", features = ["derive", "env"] }
dirs = "4.0.0"
smol_str = "0.1"
