[package]
name = "tvix-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tvix"
path = "src/main.rs"

[dependencies]
nix-compat = { path = "../nix-compat" }
tvix-eval = { path = "../eval" }
rustyline = "10.0.0"
clap = { version = "4.0", features = ["derive", "env"] }
dirs = "4.0.0"
smol_str = "0.1"
ssri = "7.0.0"
data-encoding = "2.3.3"
thiserror = "1.0.38"

[dependencies.wu-manber]
git = "https://github.com/tvlfyi/wu-manber.git"
