[package]
name = "tvix-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tvix"
path = "src/main.rs"

[dependencies]
nix-compat = { path = "../nix-compat" }
tvix-store = { path = "../store", features = []}
tvix-eval = { path = "../eval" }
bytes = "1.4.0"
clap = { version = "4.0", features = ["derive", "env"] }
dirs = "4.0.0"
rustyline = "10.0.0"
thiserror = "1.0.38"
tracing = "0.1.37"
tokio = "1.28.0"

[dependencies.wu-manber]
git = "https://github.com/tvlfyi/wu-manber.git"
