[package]
name = "tvix-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tvix-eval = { path = "../eval" }
rustyline = "10.0.0"
clap = { version = "3.2.22", features = ["derive", "env"] }
dirs = "4.0.0"
