#+TITLE: Tomato Sauce
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" href="../main.css">

This is a general, all-purpose framework for turning some form of tomatoes into
some form of sauce. You can use fresh tomatoes or canned (the latter are really
quite surprisingly good sometimes), and include or omit garlic, basil, or other
add-ins. The only real non-negotiable ingredients are tomatoes (duh), onion, and
some kind of fat (I prefer butter).

* Sauce

1. *Prep*. If starting with canned tomatoes, skip this step. if starting with
   whole tomatoes (which you should really only ever do if you grew them
   yourself or got them fresh at a farmers market, grocery store tomatoes are
   kinda sad), first, peel the tomatoes. The easiest way to do this is to score
   them with an X pattern cut as shallow as possible while still breaking the
   skin, trying to cover the whole surface area of the tomato, blanch them
   briefly in boiling water, then dunk into an ice bath. After this, the skins
   will slip right off.  After peeling, cut out the stem, core, and any green or
   brown bits, and go to the next step

2. *Base layer*. Couple of variables here, though a perfectly good (in fact, my
   usual go-to) tomato sauce can also skip this entire step:
   - If you want meat with your sauce (pancetta/guanciale/bacon for an
     amatriciana, ground beef or pork for a bolognese) you'll start out by
     sautéing that in some sort of fat (probably olive oil), less fat for meat
     with a lot of fat already in it, to brown and render out fat from the meat
   - If you want onion in the final sauce, you'll chop them finely and sauté
     them with whatever fat you've got (either from the meat, or olive oil or
     butter if you're not making a meat sauce). Remember to always add a *bit*
     of salt when sautéing onion like this, not for flavor but to draw out the
     moisture. If you just want onion flavor but not bits of onion in the final
     sauce, it's added whole later (so ignore this bullet point).
   - If you feel like it (sometimes I do, usually I don't) you can also mince
     garlic here and sauté that in with everything else. Add a little after the
     onion, as garlic cooks slower than onion unless you want something roastier
     (usually you don't for tomato sauce)
   - The traditional (so I'm told) thing to do with amatriciana, but also nice
     with all variations, is to add in a little crushed red pepper with the
     fat to flavor it slightly, but do this late so it doesn't burn
   - If you have tomato paste on hand and feel like using it, it's also nice to
     fry that in the oil for a little bit - usually I'd do that around the same
     time as the garlic

   If you're making tomato *paste* from your sauce, skip all of this - paste is
   an ingredient, not a sauce on its own, so imo should be as neutral as
   possible (eg just tomato).

3. *Tomato layer*. Not a whole lot to do here, just add all of your tomatoes -
   either your peeled and de-cored tomatoes from step 1 if you're using whole
   tomatoes, or an entire can of whole, peeled san marzano tomatoes, including
   the juice in the can - to a pot over medium-high heat. If you need more fat
   or if you skipped step 2, this is where you'd add it - a classic and my
   personal favorite is like 2/3rds to 3/4ths of a stick of butter, but you can
   also go with olive oil. If you skipped the onion in step 2, add that here
   too - usually that'd just be a fist-sized amount of onion or so peeled but
   left with the stem on so you can fish it out from your final sauce later (and
   snack on it!). Also salt here, again not to taste but primarily to draw out
   moisture from the various ingredients.

4. You can cook that for a wide variety of times, especially depending on how
   hot you make your stove - there ends up being *lot* of liquid in there, so
   you can go (in my experience) a reasonable amount hotter than you expect
   without burning the sauce, though obviously your mileage may vary. The main
   thing you're looking for is the whole chunks of tomato to break down, and the
   whole sauce to get a texture that looks like it'll end up sticking to pasta
   nicely. In all versions of this, stir pretty regularly with a wooden spoon,
   and use the spoon to crush the big chunks of tomato occasionally.

5. *Final layer*. Usually I don't do anything here - but if you feel
   like it, usually right as you take stuff off the heat is where you'd add
   basil, if you're using it. You can also add sugar to balance out too much
   acidity from an especially acidic tomato here - I'm not going to tell anyone.
   Also salt, but make sure to account for the extra salt you're gonna get from
   the pasta water (see step 6)

6. *Pasta*. You know how to cook pasta, I'm not going to tell you that. But,
   like, salt your water until it tastes too salty, and remember to move the
   pasta itself *directly* into the sauce pot from the pasta pot before it's
   completely done cooking and without straining, bringing along some of the
   pasta water (and a little extra for good measure) then finishing the pasta in
   the sauce. You know, the thing you do for pasta. Remember the pasta water
   will have salt in it, so adjust for that when salting the sauce overall (I
   have made this mistake and ended up with too-salty pasta sauce).

* Paste

Start with the above recipe for tomato sauce, noting especially that (in my
opinion) you should skip step 2 entirely. Keep cooking the sauce until it's
*too* thick for pasta sauce (but don't burn it!), then spread it out across some
sort of lined sheet pan (like a silpat, if you've got one) and bake in the oven
at like 250-300 degrees for a *hell* of a long time - I've seen this take like
10 hours, for an especially juicy batch of tomatoes, but obviously keep a close
eye on it because it *definitely will burn* eventually. You're looking for the
end result to be the texture of tomato paste, because that's what the recipe is
for.  Especially if you're using garden-grown or otherwise fresh tomatoes,
you'll notice quite a few seeds in the final product - don't worry too much
about those, they've never bothered me. Once everything's done and cooled down,
store in a jar in a fridge, topped with olive oil to seal things off and prevent
oxidation. Use in all your future endeavors, including the tomato sauce recipe
above itself. Tomato sauce is a beautiful oroborous.
