# SPDX-FileCopyrightText: edef <edef@edef.eu>
# SPDX-License-Identifier: MPL-2.0

[package]
name = "refscan"
version = "0.1.0"
authors = ["edef <edef@edef.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
