[package]
name = "tvix-castore"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
blake3 = { version = "1.3.1", features = ["rayon", "std"] }
bytes = "1.4.0"
data-encoding = "2.3.3"
futures = "0.3.28"
lazy_static = "1.4.0"
pin-project-lite = "0.2.13"
prost = "0.12.1"
sled = { version = "0.34.7", features = ["compression"] }
thiserror = "1.0.38"
tokio-stream = { version = "0.1.14", features = ["fs", "net"] }
tokio-util = { version = "0.7.9", features = ["io", "io-util"] }
tokio = { version = "1.32.0", features = ["fs", "macros", "net", "rt", "rt-multi-thread", "signal"] }
tonic = "0.10.2"
tower = "0.4.13"
tracing = "0.1.37"
url = "2.4.0"
walkdir = "2.4.0"
bstr = "1.6.0"

[dependencies.tonic-reflection]
optional = true
version = "0.10.2"

[build-dependencies]
prost-build = "0.12.1"
tonic-build = "0.10.2"

[dev-dependencies]
test-case = "2.2.2"
tempfile = "3.3.0"
tokio-retry = "0.3.0"
hex-literal = "0.4.1"

[features]
default = []
tonic-reflection = ["dep:tonic-reflection"]
