[package]
name = "tvix-castore"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
blake3 = { version = "1.3.1", features = ["rayon", "std"] }
bytes = "1.4.0"
data-encoding = "2.3.3"
futures = "0.3.28"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
pin-project-lite = "0.2.13"
prost = "0.12.1"
sled = { version = "0.34.7" }
thiserror = "1.0.38"
tokio-stream = { version = "0.1.14", features = ["fs", "net"] }
tokio-util = { version = "0.7.9", features = ["io", "io-util"] }
tokio = { version = "1.32.0", features = ["fs", "macros", "net", "rt", "rt-multi-thread", "signal"] }
tonic = "0.10.2"
tower = "0.4.13"
tracing = "0.1.37"
url = "2.4.0"
walkdir = "2.4.0"
bstr = "1.6.0"
async-tempfile = "0.4.0"

[dependencies.fuse-backend-rs]
optional = true
version = "0.11.0"

[dependencies.libc]
optional = true
version = "0.2.144"

[dependencies.tonic-reflection]
optional = true
version = "0.10.2"

[dependencies.vhost]
optional = true
version = "0.6"

[dependencies.vhost-user-backend]
optional = true
version = "0.8"

[dependencies.virtio-queue]
optional = true
version = "0.7"

[dependencies.vm-memory]
optional = true
version = "0.10"

[dependencies.vmm-sys-util]
optional = true
version = "0.11"

[dependencies.virtio-bindings]
optional = true
version = "0.2.1"

[build-dependencies]
prost-build = "0.12.1"
tonic-build = "0.10.2"

[dev-dependencies]
test-case = "2.2.2"
tempfile = "3.3.0"
tokio-retry = "0.3.0"
hex-literal = "0.4.1"

[features]
default = []
fs = ["dep:libc", "dep:fuse-backend-rs"]
virtiofs = [
  "fs",
  "dep:vhost",
  "dep:vhost-user-backend",
  "dep:virtio-queue",
  "dep:vm-memory",
  "dep:vmm-sys-util",
  "dep:virtio-bindings",
  "fuse-backend-rs?/vhost-user-fs", # impl FsCacheReqHandler for SlaveFsCacheReq
  "fuse-backend-rs?/virtiofs",
]
fuse = ["fs"]
tonic-reflection = ["dep:tonic-reflection"]
